In [50]:
import pandas as pd
temp = pd.read_csv("GlobalLandTemperaturesByCountry.csv")
temp = temp.dropna()
temp.head()
temp = temp[temp["Country"] != "Åland"]
temp

,dt,AverageTemperature,AverageTemperatureUncertainty,Country
3239,1838-04-01,13.008,2.586,Afghanistan
3241,1838-06-01,23.950,2.510,Afghanistan
3242,1838-07-01,26.877,2.883,Afghanistan
3243,1838-08-01,24.938,2.992,Afghanistan
3244,1838-09-01,18.981,2.538,Afghanistan
3245,1838-10-01,13.428,3.039,Afghanistan
3246,1838-11-01,7.475,2.744,Afghanistan
3260,1840-01-01,0.735,2.492,Afghanistan
3261,1840-02-01,1.661,2.563,Afghanistan
3262,1840-03-01,6.513,2.402,Afghanistan
3263,1840-04-01,13.965,2.617,Afghanistan
3264,1840-05-01,19.618,2.516,Afghanistan
3265,1840-06-01,24.812,2.466,Afghanistan
3266,1840-07-01,27.739,2.353,Afghanistan
3267,1840-08-01,24.812,2.343,Afghanistan
3268,1840-09-01,18.989,2.366,Afghanistan
3270,1840-11-01,6.773,2.862,Afghanistan
3271,1840-12-01,1.931,2.542,Afghanistan
3272,1841-01-01,-0.883,2.471,Afghanistan
3274,1841-03-01,5.521,3.008,Afghanistan
3275,1841-04-01,12.556,2.423,Afghanistan
3276,1841-05-01,19.614,2.322,Afghanistan
3277,1841-06-01,24.251,2.358,Afghanistan
3278,1841-07-01,27.104,2.445,Afghanistan
3279,1841-08-01,24.687,2.423,Afghanistan
3280,1841-09-01,19.014,2.325,Afghanistan
3282,1841-11-01,6.754,2.332,Afghanistan
3283,1841-12-01,1.358,2.414,Afghanistan
3286,1842-03-01,9.489,2.691,Afghanistan
3287,1842-04-01,14.983,2.428,Afghanistan
...,...,...,...,...
577431,2011-03-01,23.668,0.183,Zimbabwe
577432,2011-04-01,21.759,0.319,Zimbabwe
577433,2011-05-01,19.627,0.398,Zimbabwe
577434,2011-06-01,16.939,0.599,Zimbabwe
577435,2011-07-01,15.803,0.447,Zimbabwe
577436,2011-08-01,17.883,0.328,Zimbabwe
577437,2011-09-01,22.902,0.612,Zimbabwe
577438,2011-10-01,24.966,0.441,Zimbabwe
577439,2011-11-01,25.521,0.318,Zimbabwe
577440,2011-12-01,24.013,0.356,Zimbabwe
577441,2012-01-01,23.872,0.247,Zimbabwe
577442,2012-02-01,24.294,0.305,Zimbabwe
577443,2012-03-01,23.596,0.354,Zimbabwe
577444,2012-04-01,20.349,0.462,Zimbabwe
577445,2012-05-01,19.712,0.312,Zimbabwe
577446,2012-06-01,16.631,0.277,Zimbabwe
577447,2012-07-01,16.048,0.783,Zimbabwe
577448,2012-08-01,18.946,1.127,Zimbabwe
577449,2012-09-01,22.609,0.643,Zimbabwe
577450,2012-10-01,23.482,0.574,Zimbabwe
577451,2012-11-01,24.606,0.532,Zimbabwe
577452,2012-12-01,24.111,0.846,Zimbabwe
577453,2013-01-01,23.812,1.218,Zimbabwe
577454,2013-02-01,24.075,1.286,Zimbabwe
577455,2013-03-01,23.226,0.564,Zimbabwe
577456,2013-04-01,21.142,0.495,Zimbabwe
577457,2013-05-01,19.059,1.022,Zimbabwe
577458,2013-06-01,17.613,0.473,Zimbabwe
577459,2013-07-01,17.000,0.453,Zimbabwe
577460,2013-08-01,19.759,0.717,Zimbabwe

In [51]:
tempDf = temp.groupby("Country").mean()
#tempDf.head(100)
# faire ue liste de noms de pays et la mettre dans tempDf["Country"]
#faire l'etude par année(diviser le dataframe sur 5 années différentes)

In [52]:
temp1 = temp[(temp["dt"] >=  "1743-01-01")]
temp1 = temp1[(temp["dt"] <  "1844-01-01")]
#temp1

In [53]:
temp1_moy = temp1.groupby("Country").mean()
temp1_moy

,AverageTemperature,AverageTemperatureUncertainty
Country,,
Afghanistan,14.645878,2.469449
Albania,12.427831,3.122952
Algeria,22.681368,2.308665
Andorra,11.040743,3.248353
Anguilla,26.478323,1.733569
Antigua And Barbuda,26.289831,1.749462
Armenia,7.925873,2.860532
Aruba,27.764877,1.598569
Asia,6.890412,1.679185
Austria,6.055523,3.506757
Azerbaijan,10.480688,2.725136
Bahamas,24.976803,2.342943
Bahrain,25.336727,1.922727
Baker Island,24.822222,1.430667
Bangladesh,24.449174,1.947339
Barbados,26.278354,1.835615
Belarus,5.610799,3.419923
Belgium,9.289842,3.639624
Belize,24.621394,1.770263
Bhutan,11.386131,1.927587
"Bonaire, Saint Eustatius And Saba",27.014415,1.638323
Bosnia And Herzegovina,10.271165,3.333590
Brazil,24.009535,1.385840
British Virgin Islands,26.222015,1.753985
Bulgaria,10.283532,3.217556
Burma,23.224706,1.726068
Cambodia,26.364536,1.644261
Canada,-5.894191,2.816649
Cayman Islands,26.424381,1.914786
China,6.061012,1.556000
...,...,...
Sint Maarten,26.478323,1.733569
Slovakia,7.375582,3.448920
Slovenia,9.513511,3.445222
South Korea,11.159833,2.132222
Spain,13.439829,3.058299
Sri Lanka,26.548651,1.989832
Suriname,26.029508,1.486862
Svalbard And Jan Mayen,-7.662360,4.901043
Sweden,2.139822,3.653365
Switzerland,6.833065,3.559556
Syria,17.198208,2.531404
Taiwan,21.384472,1.779139
Tajikistan,3.340344,2.539861
Thailand,25.446308,1.810756
Trinidad And Tobago,25.954523,1.760292
Tunisia,19.777277,2.898987
Turkey,11.322996,2.838748
Turkmenistan,13.781530,3.135579
Turks And Caicas Islands,26.362687,1.842075
Ukraine,7.420482,3.349537
United Arab Emirates,27.233909,1.608545
United Kingdom,8.262864,3.444404
United Kingdom (Europe),8.430491,3.512844
United States,7.915256,2.409373
Uruguay,16.447125,2.225979
Uzbekistan,11.244181,3.254100
Venezuela,24.907446,1.550738
Vietnam,23.477333,1.638333
Virgin Islands,26.222015,1.753985
Western Sahara,21.935583,2.278397

In [54]:
type(temp1["Country"])
c = temp1["Country"]
cval = c.values
countries = pd.unique(cval)
len(countries)
temp1_moy["country"] = countries

#deplac = temp1_moy.iloc[0,2]
#temp1_moy.iloc[0,2] = temp1_moy.iloc[-1,2]
#temp1_moy.iloc[-1,2] = deplac
temp1_moy

,AverageTemperature,AverageTemperatureUncertainty,country
Country,,,
Afghanistan,14.645878,2.469449,Afghanistan
Albania,12.427831,3.122952,Albania
Algeria,22.681368,2.308665,Algeria
Andorra,11.040743,3.248353,Andorra
Anguilla,26.478323,1.733569,Anguilla
Antigua And Barbuda,26.289831,1.749462,Antigua And Barbuda
Armenia,7.925873,2.860532,Armenia
Aruba,27.764877,1.598569,Aruba
Asia,6.890412,1.679185,Asia
Austria,6.055523,3.506757,Austria
Azerbaijan,10.480688,2.725136,Azerbaijan
Bahamas,24.976803,2.342943,Bahamas
Bahrain,25.336727,1.922727,Bahrain
Baker Island,24.822222,1.430667,Baker Island
Bangladesh,24.449174,1.947339,Bangladesh
Barbados,26.278354,1.835615,Barbados
Belarus,5.610799,3.419923,Belarus
Belgium,9.289842,3.639624,Belgium
Belize,24.621394,1.770263,Belize
Bhutan,11.386131,1.927587,Bhutan
"Bonaire, Saint Eustatius And Saba",27.014415,1.638323,"Bonaire, Saint Eustatius And Saba"
Bosnia And Herzegovina,10.271165,3.333590,Bosnia And Herzegovina
Brazil,24.009535,1.385840,Brazil
British Virgin Islands,26.222015,1.753985,British Virgin Islands
Bulgaria,10.283532,3.217556,Bulgaria
Burma,23.224706,1.726068,Burma
Cambodia,26.364536,1.644261,Cambodia
Canada,-5.894191,2.816649,Canada
Cayman Islands,26.424381,1.914786,Cayman Islands
China,6.061012,1.556000,China
...,...,...,...
Sint Maarten,26.478323,1.733569,Sint Maarten
Slovakia,7.375582,3.448920,Slovakia
Slovenia,9.513511,3.445222,Slovenia
South Korea,11.159833,2.132222,South Korea
Spain,13.439829,3.058299,Spain
Sri Lanka,26.548651,1.989832,Sri Lanka
Suriname,26.029508,1.486862,Suriname
Svalbard And Jan Mayen,-7.662360,4.901043,Svalbard And Jan Mayen
Sweden,2.139822,3.653365,Sweden
Switzerland,6.833065,3.559556,Switzerland
Syria,17.198208,2.531404,Syria
Taiwan,21.384472,1.779139,Taiwan
Tajikistan,3.340344,2.539861,Tajikistan
Thailand,25.446308,1.810756,Thailand
Trinidad And Tobago,25.954523,1.760292,Trinidad And Tobago
Tunisia,19.777277,2.898987,Tunisia
Turkey,11.322996,2.838748,Turkey
Turkmenistan,13.781530,3.135579,Turkmenistan
Turks And Caicas Islands,26.362687,1.842075,Turks And Caicas Islands
Ukraine,7.420482,3.349537,Ukraine
United Arab Emirates,27.233909,1.608545,United Arab Emirates
United Kingdom,8.262864,3.444404,United Kingdom (Europe)
United Kingdom (Europe),8.430491,3.512844,United Kingdom
United States,7.915256,2.409373,United States
Uruguay,16.447125,2.225979,Uruguay
Uzbekistan,11.244181,3.254100,Uzbekistan
Venezuela,24.907446,1.550738,Venezuela
Vietnam,23.477333,1.638333,Vietnam
Virgin Islands,26.222015,1.753985,Virgin Islands
Western Sahara,21.935583,2.278397,Western Sahara

In [6]:
vehicules.to_csv('179.csv', index=False)

NameError: name 'vehicules' is not defined