In [20]:
import pandas as pd
temp = pd.read_csv("DataTemp.csv")

temp.head()
a = temp["dt"]
type(a)
r = a.str.findall("12-01")
r

pandas.core.series.Series

In [17]:
cities = temp.filter(like='Abidjan', axis=0)
temp.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W

In [9]:

#temp1

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [11]:
temp1_moy = temp1.groupby("City")
temp1_moy

                  AverageTemperature  AverageTemperatureUncertainty
City
Abidjan                    27.017583                       0.290167
Addis Abeba                18.606750                       0.895583
Ahmadabad                  27.290417                       0.419083
Aleppo                     18.016583                       0.440250
Alexandria                 21.181500                       0.303083
Ankara                     10.389667                       0.328917
Baghdad                    23.437500                       0.274417
Bangalore                  25.362083                       0.332417
Bangkok                    27.558333                       0.360167
Belo Horizonte             21.740500                       0.354500
Berlin                     10.556417                       0.266583
Bogotá                     20.544250                       0.422750
Bombay                     27.384917                       0.339583
Brasília                   22.387167                       0.360667
Cairo                      21.986917                       0.296917
Calcutta                   26.406917                       0.327500
Cali                       22.330000                       0.398417
Cape Town                  16.621083                       0.526917
Casablanca                 18.533083                       0.600250
Changchun                   5.758667                       0.421000
Chengdu                    11.074333                       0.468583
Chicago                    11.214250                       0.401750
Chongqing                  17.382917                       0.298333
Dakar                      25.411000                       0.539750
Dalian                     10.913583                       0.353500
Dar Es Salaam              26.557917                       0.318083
Delhi                      25.629500                       0.427250
Dhaka                      25.803250                       0.385583
Durban                     20.722333                       0.471250
Faisalabad                 24.975250                       0.353917
...                              ...                            ...
New Delhi                  25.629500                       0.427250
New York                   11.272250                       0.296750
Paris                      12.325750                       0.246583
Peking                     12.770250                       0.416667
Pune                       25.161417                       0.298750
Rangoon                    27.203250                       0.393667
Rio De Janeiro             24.319833                       0.375083
Riyadh                     26.396750                       0.506250
Rome                       13.463167                       0.406917
Saint Petersburg            6.056250                       0.301250
Salvador                   25.283667                       0.484250
Santiago                    6.268583                       0.376083
Santo Domingo              26.663500                       0.331000
Seoul                      11.122417                       0.309333
Shanghai                   16.518000                       0.248917
Shenyang                    8.043833                       0.309583
Singapore                  27.282167                       0.274083
Surabaya                   27.190250                       0.282750
Surat                      27.016583                       0.319500
Sydney                     17.713333                       0.206750
São Paulo                  20.330083                       0.343167
Taipei                     22.551833                       0.263333
Taiyuan                     8.643167                       0.305167
Tangshan                   12.258833                       0.319250
Tianjin                    12.770250                       0.416667
Tokyo                      13.321833                       0.229833
Toronto                     7.299583                       0.281417
Umm Durman                 29.963667                       0.896000
Wuhan                      17.387583                       0.315417
Xian                       12.075167                       0.390583

[100 rows x 2 columns]

In [12]:
type(temp1["City"])
c = temp1["City"]
cval = c.values
countries = pd.unique(cval)
len(countries)
temp1_moy["City"] = countries

#deplac = temp1_moy.iloc[0,2]
#temp1_moy.iloc[0,2] = temp1_moy.iloc[-1,2]
#temp1_moy.iloc[-1,2] = deplac
temp1_moy

,AverageTemperature,AverageTemperatureUncertainty,City
City,,,
Abidjan,27.017583,0.290167,Abidjan
Addis Abeba,18.606750,0.895583,Addis Abeba
Ahmadabad,27.290417,0.419083,Ahmadabad
Aleppo,18.016583,0.440250,Aleppo
Alexandria,21.181500,0.303083,Alexandria
Ankara,10.389667,0.328917,Ankara
Baghdad,23.437500,0.274417,Baghdad
Bangalore,25.362083,0.332417,Bangalore
Bangkok,27.558333,0.360167,Bangkok
Belo Horizonte,21.740500,0.354500,Belo Horizonte
Berlin,10.556417,0.266583,Berlin
Bogotá,20.544250,0.422750,Bogotá
Bombay,27.384917,0.339583,Bombay
Brasília,22.387167,0.360667,Brasília
Cairo,21.986917,0.296917,Cairo
Calcutta,26.406917,0.327500,Calcutta
Cali,22.330000,0.398417,Cali
Cape Town,16.621083,0.526917,Cape Town
Casablanca,18.533083,0.600250,Casablanca
Changchun,5.758667,0.421000,Changchun
Chengdu,11.074333,0.468583,Chengdu
Chicago,11.214250,0.401750,Chicago
Chongqing,17.382917,0.298333,Chongqing
Dakar,25.411000,0.539750,Dakar
Dalian,10.913583,0.353500,Dalian
Dar Es Salaam,26.557917,0.318083,Dar Es Salaam
Delhi,25.629500,0.427250,Delhi
Dhaka,25.803250,0.385583,Dhaka
Durban,20.722333,0.471250,Durban
Faisalabad,24.975250,0.353917,Faisalabad
...,...,...,...
New Delhi,25.629500,0.427250,New Delhi
New York,11.272250,0.296750,New York
Paris,12.325750,0.246583,Paris
Peking,12.770250,0.416667,Peking
Pune,25.161417,0.298750,Pune
Rangoon,27.203250,0.393667,Rangoon
Rio De Janeiro,24.319833,0.375083,Rio De Janeiro
Riyadh,26.396750,0.506250,Riyadh
Rome,13.463167,0.406917,Rome
Saint Petersburg,6.056250,0.301250,São Paulo
Salvador,25.283667,0.484250,Saint Petersburg
Santiago,6.268583,0.376083,Salvador
Santo Domingo,26.663500,0.331000,Santiago
Seoul,11.122417,0.309333,Santo Domingo
Shanghai,16.518000,0.248917,Seoul
Shenyang,8.043833,0.309583,Shanghai
Singapore,27.282167,0.274083,Shenyang
Surabaya,27.190250,0.282750,Singapore
Surat,27.016583,0.319500,Surabaya
Sydney,17.713333,0.206750,Surat
São Paulo,20.330083,0.343167,Sydney
Taipei,22.551833,0.263333,Taipei
Taiyuan,8.643167,0.305167,Taiyuan
Tangshan,12.258833,0.319250,Tangshan
Tianjin,12.770250,0.416667,Tianjin
Tokyo,13.321833,0.229833,Tokyo
Toronto,7.299583,0.281417,Toronto
Umm Durman,29.963667,0.896000,Umm Durman
Wuhan,17.387583,0.315417,Wuhan
Xian,12.075167,0.390583,Xian

In [14]:
temp1_moy = temp1_moy.drop(["AverageTemperatureUncertainty"],axis=1)

KeyError: "['AverageTemperatureUncertainty'] not found in axis"

In [15]:
temp1_moy.to_csv('2012 cities.csv', index=False)

In [25]:
temp2 = temp[(temp["dt"] >=  "1844-01-01")]
temp2 = temp2[(temp2["dt"] <  "1945-01-01")]
temp2_moy = temp2.groupby("Country").mean()
c = temp2["Country"]
cval = c.values
countries = pd.unique(cval)
len(countries)
temp2_moy["country"] = countries
temp2_moy = temp2_moy.drop(["AverageTemperatureUncertainty"],axis=1)
temp2_moy.to_csv('1844-1945.csv', index=False)
temp2_moy

,AverageTemperature,country
Country,,
Afghanistan,13.718510,Afghanistan
Africa,23.814479,Africa
Albania,12.484180,Albania
Algeria,22.810849,Algeria
American Samoa,26.296995,American Samoa
Andorra,11.013523,Andorra
Angola,21.537013,Angola
Anguilla,26.327997,Anguilla
Antigua And Barbuda,26.154864,Antigua And Barbuda
Argentina,14.330684,Argentina
Armenia,8.379282,Armenia
Aruba,27.646786,Aruba
Asia,7.108617,Asia
Australia,21.413293,Australia
Austria,5.992630,Austria
Azerbaijan,10.982427,Azerbaijan
Bahamas,24.923630,Bahamas
Bahrain,25.623424,Bahrain
Baker Island,25.061746,Baker Island
Bangladesh,24.677817,Bangladesh
Barbados,26.170163,Barbados
Belarus,5.606575,Belarus
Belgium,9.314773,Belgium
Belize,24.824923,Belize
Benin,26.900261,Benin
Bhutan,11.649331,Bhutan
Bolivia,20.619194,Bolivia
"Bonaire, Saint Eustatius And Saba",26.895592,"Bonaire, Saint Eustatius And Saba"
Bosnia And Herzegovina,10.235292,Bosnia And Herzegovina
Botswana,21.589572,Botswana
...,...,...
Sweden,2.248858,Sweden
Switzerland,6.773068,Switzerland
Syria,17.804059,Syria
Taiwan,21.644645,Taiwan
Tajikistan,3.715019,Tajikistan
Tanzania,22.094053,Tanzania
Thailand,25.780543,Thailand
Timor Leste,25.675151,Timor Leste
Togo,26.591110,Togo
Tonga,22.901019,Tonga
Trinidad And Tobago,25.826078,Trinidad And Tobago
Tunisia,19.800469,Tunisia
Turkey,11.515206,Turkey
Turkmenistan,14.498376,Turkmenistan
Turks And Caicas Islands,26.440433,Turks And Caicas Islands
Uganda,22.784684,Uganda
Ukraine,7.466603,Ukraine
United Arab Emirates,27.369710,United Arab Emirates
United Kingdom,8.399121,United Kingdom (Europe)
United Kingdom (Europe),8.569718,United Kingdom
United States,8.516126,United States
Uruguay,16.917343,Uruguay
Uzbekistan,11.988076,Uzbekistan
Venezuela,24.736840,Venezuela
Vietnam,23.431112,Vietnam
Virgin Islands,26.052433,Virgin Islands
Western Sahara,22.160456,Western Sahara
Yemen,25.969142,Yemen
Zambia,21.006801,Zambia
Zimbabwe,20.828092,Zimbabwe

In [24]:
temperature = temp[(temp["dt"] >=  "2013-01-01")]
temperature = temperature[(temperature["dt"] <=  "2013-12-31")]
temperature_moy = temperature.groupby("Country").mean()
c = temperature["Country"]
cval = c.values
countries = pd.unique(cval)
len(countries)
temperature_moy["country"] = countries
temperature_moy = temperature_moy.drop(["AverageTemperatureUncertainty"],axis=1)
temperature_moy.to_csv('2013.csv', index=False)
temperature_moy

,AverageTemperature,country
Country,,
Afghanistan,16.533625,Afghanistan
Africa,25.208750,Africa
Albania,14.993875,Albania
Algeria,25.121500,Algeria
American Samoa,27.517250,American Samoa
Andorra,12.307875,Andorra
Angola,22.507875,Angola
Anguilla,27.363000,Anguilla
Antigua And Barbuda,27.249625,Antigua And Barbuda
Argentina,14.457125,Argentina
Armenia,11.343750,Armenia
Aruba,28.541250,Aruba
Asia,10.047375,Asia
Australia,22.142875,Australia
Austria,8.055125,Austria
Azerbaijan,14.173875,Azerbaijan
Bahamas,26.011667,Bahamas
Bahrain,27.925375,Bahrain
Baker Island,26.431750,Baker Island
Bangladesh,25.967500,Bangladesh
Barbados,27.251125,Barbados
Belarus,8.266500,Belarus
Belgium,10.060125,Belgium
Belize,26.213333,Belize
Benin,28.160625,Benin
Bhutan,13.331375,Bhutan
Bolivia,20.640875,Bolivia
"Bonaire, Saint Eustatius And Saba",27.919625,"Bonaire, Saint Eustatius And Saba"
Bosnia And Herzegovina,12.879500,Bosnia And Herzegovina
Botswana,21.825750,Botswana
...,...,...
Sweden,4.199750,Sweden
Switzerland,8.177500,Switzerland
Syria,20.021125,Syria
Taiwan,23.015000,Taiwan
Tajikistan,6.562625,Tajikistan
Tanzania,22.772750,Tanzania
Thailand,27.864875,Thailand
Timor Leste,26.312500,Timor Leste
Togo,27.718000,Togo
Tonga,24.285875,Tonga
Trinidad And Tobago,27.086625,Trinidad And Tobago
Tunisia,21.887125,Tunisia
Turkey,14.026625,Turkey
Turkmenistan,18.613500,Turkmenistan
Turks And Caicas Islands,27.440556,Turks And Caicas Islands
Uganda,24.024625,Uganda
Ukraine,10.913500,Ukraine
United Arab Emirates,29.370625,United Arab Emirates
United Kingdom,8.997500,United Kingdom (Europe)
United Kingdom (Europe),9.108250,United Kingdom
United States,11.297111,United States
Uruguay,16.754375,Uruguay
Uzbekistan,16.188250,Uzbekistan
Venezuela,25.912875,Venezuela
Vietnam,25.232125,Vietnam
Virgin Islands,27.312333,Virgin Islands
Western Sahara,23.744250,Western Sahara
Yemen,28.129750,Yemen
Zambia,21.196000,Zambia
Zimbabwe,20.710750,Zimbabwe